#define PIN_CLOCK_INPUT 1
#define PIN_RESET_INPUT 0

#define PIN_CLOCK_BUTTON 2
#define PIN_RESET_BUTTON 3

#define PIN_SWITCH_A 5
#define PIN_SWITCH_B 6

#define DISPLAY_I2C_ADDRESS 0x03
#define EEPROM_I2C_ADDRESS 0x50  // 80 decimal
#define DAC_I2C_ADDRESS 0x60     // 90 decimal

#define TOP_DISPLAY 0
#define BOTTOM_DISPLAY 1

#define SEQUENCE_PLAYBACK_MODE 0
#define SEQUENCE_EDIT_MODE 1
#define SETTINGS_MODE 2

#define MAX_SEQUENCE_LENGTH 64 // max 256 to fit into 1 byte

#define MEM_ADDR_SEQUENCE_LENGTH 130
#define MEM_ADDR_CLOCK_DIVISION 132
#define MEM_ADDR_QUANTIZATION 134
#define MEM_ADDR_SELF_INITIALIZATION 136
#define MEM_ADDR_SCALE 138
#define MEM_ADDR_INTENSITY 140
#define MEM_ADDR_SLIP 142
#define MEM_ADDR_DRIFT_PERCENTAGE 144
#define MEM_ADDR_DRIFT_AMOUNT 146
#define MEM_ADDR_HOLD 148
#define MEM_ADDR_SONG 150
#define MEM_ADDR_SONG2 152

// define NUMBER_OF_SNAPSHOTS 4
#define NUMBER_OF_SETTINGS_PAGES 12
#define NUMBER_OF_SCALES 14
#define NUMBER_OF_SONGS 16
